import type { Feature, Product } from "./types";
import {
  bundles,
  chairColors,
  chairSpecs,
  chairStory,
  delivery,
  fitnessSpecs,
  L,
} from "./product-details";

/** Xususiyatlar — ikon + qisqa yorliq (kartada ikon bilan ko'rsatiladi). */
const f = {
  zeroG:    { icon: "zero-gravity", label: { ru: "Невесомость",       uz: "Vaznsizlik",         en: "Zero gravity" } },
  scan:     { icon: "body-scan",    label: { ru: "Сканирование тела", uz: "Tana skaneri",       en: "Body scan" } },
  bt:       { icon: "bluetooth",    label: { ru: "Bluetooth",         uz: "Bluetooth",          en: "Bluetooth" } },
  heat:     { icon: "heat",         label: { ru: "Прогрев спины",     uz: "Bel isitish",        en: "Back heating" } },
  sl:       { icon: "sl-track",     label: { ru: "SL-направляющая",   uz: "SL-yo‘naltirgich",   en: "SL-track" } },
  air:      { icon: "air",          label: { ru: "Воздушные подушки", uz: "Havo yostiqchalari", en: "Air cushions" } },
  foldable: { icon: "folding",      label: { ru: "Складная рама",     uz: "Yig‘iladigan ramka", en: "Folding frame" } },
  quiet:    { icon: "quiet",        label: { ru: "Тихий привод",      uz: "Tinch dvigatel",     en: "Quiet drive" } },
} satisfies Record<string, Feature>;

export const products: Product[] = [
  {
    _id: "p-crown-2", slug: "crown-2", rank: 1, category: "massage-chairs",
    isNew: true, price: 1_690_000, oldPrice: 1_890_000, currency: "UZS",
    title: { ru: "Массажное кресло Crown 2 от iSpace", uz: "iSpace Crown 2 massaj kreslosi", en: "iSpace Crown 2 massage chair" },
    features: [f.zeroG, f.scan, f.bt],
    images: [{ src: "/images/products/crown-2.webp", width: 900, height: 900,
      alt: { ru: "Массажное кресло Crown 2", uz: "Crown 2 massaj kreslosi", en: "Crown 2 massage chair" } }],
    brand: "iSpace", rating: 4.9, reviewCount: 124, inStock: true,
    description: L(
      "Crown 2 — премиальное массажное кресло для полноценного расслабления. Технология 4D-массажа имитирует движения рук профессионала, а режим невесомости снимает нагрузку с позвоночника.",
      "Crown 2 — to‘liq bo‘shashish uchun premium massaj kreslosi. 4D-massaj texnologiyasi professional qo‘l harakatlarini takrorlaydi, vaznsizlik rejimi esa umurtqadan yukni oladi.",
      "Crown 2 is a premium massage chair built for complete relaxation. Its 4D massage mimics a professional's hands, while zero gravity takes the load off your spine.",
    ),
    specs: chairSpecs({ model: "Crown 2", tech: "4D", programs: "12", power: "200 Вт", maxWeight: "120 кг", size: "1650 × 760 × 830 мм" }),
    delivery, colors: chairColors, bundles, story: chairStory("crown-2", "Crown 2"),
  },
  {
    _id: "p-takumi", slug: "takumi", rank: 2, category: "massage-chairs",
    isNew: true, price: 1_790_000, currency: "UZS",
    title: { ru: "Массажное кресло Takumi от iSpace", uz: "iSpace Takumi massaj kreslosi", en: "iSpace Takumi massage chair" },
    features: [f.sl, f.heat, f.air],
    images: [{ src: "/images/products/takumi.webp", width: 900, height: 900,
      alt: { ru: "Массажное кресло Takumi", uz: "Takumi massaj kreslosi", en: "Takumi massage chair" } }],
    brand: "iSpace", rating: 4.8, reviewCount: 86, inStock: true,
    description: L(
      "Takumi собран вокруг SL-направляющей: ролики идут по всей линии от шеи до бёдер. Прогрев поясницы и воздушные подушки завершают сеанс мягким расслаблением.",
      "Takumi SL-yo‘naltirgich atrofida qurilgan: roliklar bo‘yindan songacha butun chiziq bo‘ylab yuradi. Bel isitish va havo yostiqchalari seansni yumshoq yakunlaydi.",
      "Takumi is built around an SL-track: the rollers travel the full line from neck to hips. Lumbar heating and air cushions finish the session gently.",
    ),
    specs: chairSpecs({ model: "Takumi", tech: "3D + SL", programs: "10", power: "180 Вт", maxWeight: "120 кг", size: "1600 × 750 × 820 мм" }),
    delivery, colors: chairColors, bundles, story: chairStory("takumi", "Takumi"),
  },
  {
    _id: "p-sfera", slug: "sfera", rank: 3, category: "massage-chairs",
    price: 1_990_000, currency: "UZS",
    title: { ru: "Массажное кресло Sfera от iSpace", uz: "iSpace Sfera massaj kreslosi", en: "iSpace Sfera massage chair" },
    features: [f.zeroG, f.heat, f.bt],
    images: [{ src: "/images/products/sfera.webp", width: 900, height: 900,
      alt: { ru: "Массажное кресло Sfera", uz: "Sfera massaj kreslosi", en: "Sfera massage chair" } }],
    brand: "iSpace", rating: 4.7, reviewCount: 51, inStock: true,
    description: L(
      "Sfera — компактное кресло для дома: занимает мало места у стены, но сохраняет полный сеанс с невесомостью, прогревом и Bluetooth-аудио.",
      "Sfera — uy uchun ixcham kreslo: devor yonida kam joy egallaydi, ammo vaznsizlik, isitish va Bluetooth-audio bilan to‘liq seansni saqlaydi.",
      "Sfera is a compact chair for the home: it needs little wall clearance yet keeps a full session with zero gravity, heating and Bluetooth audio.",
    ),
    specs: chairSpecs({ model: "Sfera", tech: "3D", programs: "8", power: "160 Вт", maxWeight: "110 кг", size: "1550 × 730 × 800 мм" }),
    delivery, colors: chairColors, bundles, story: chairStory("sfera", "Sfera"),
  },
  {
    _id: "p-runner-x3", slug: "runner-x3", rank: 4, category: "treadmills",
    price: 12_990_000, currency: "UZS",
    title: { ru: "Беговая дорожка iSpace Runner X3", uz: "iSpace Runner X3 yugurish yo‘lakchasi", en: "iSpace Runner X3 treadmill" },
    features: [f.foldable, f.quiet],
    images: [{ src: "/images/products/runner-x3.webp", width: 900, height: 900,
      alt: { ru: "Беговая дорожка Runner X3", uz: "Runner X3 yugurish yo‘lakchasi", en: "Runner X3 treadmill" } }],
    brand: "iSpace", rating: 4.6, reviewCount: 38, inStock: true,
    description: L(
      "Runner X3 — беговая дорожка для квартиры: складная рама, тихий привод и амортизация, которая бережёт колени при ежедневных пробежках.",
      "Runner X3 — kvartira uchun yugurish yo‘lakchasi: yig‘iladigan ramka, tinch dvigatel va har kungi yugurishda tizzani asraydigan amortizatsiya.",
      "Runner X3 is a treadmill for apartments: a folding frame, a quiet drive and cushioning that protects your knees on daily runs.",
    ),
    specs: fitnessSpecs({ model: "Runner X3", type: L("Беговая дорожка", "Yugurish yo‘lakchasi", "Treadmill"), power: "2.5 л.с.", maxWeight: "130 кг", size: "1800 × 850 × 1350 мм" }),
    delivery,
  },
  {
    _id: "p-prestige-pro", slug: "prestige-pro", rank: 5, category: "massage-chairs",
    price: 17_990_000, oldPrice: 19_500_000, currency: "UZS",
    title: { ru: "Массажное кресло Prestige Pro", uz: "Prestige Pro massaj kreslosi", en: "Prestige Pro massage chair" },
    features: [f.scan, f.sl, f.air],
    images: [{ src: "/images/products/prestige-pro.webp", width: 900, height: 900,
      alt: { ru: "Массажное кресло Prestige Pro", uz: "Prestige Pro massaj kreslosi", en: "Prestige Pro massage chair" } }],
    brand: "iSpace", rating: 5, reviewCount: 42, inStock: true,
    description: L(
      "Prestige Pro — флагман линейки: сканирование тела перед сеансом, SL-направляющая на всю спину и полный набор воздушных подушек от плеч до стоп.",
      "Prestige Pro — liniyaning flagmani: seansdan oldin tana skaneri, butun bel bo‘ylab SL-yo‘naltirgich va yelkadan oyoqqacha to‘liq havo yostiqchalari.",
      "Prestige Pro is the flagship: a body scan before each session, a full-back SL-track and a complete set of air cushions from shoulders to feet.",
    ),
    specs: chairSpecs({ model: "Prestige Pro", tech: "4D + SL", programs: "16", power: "220 Вт", maxWeight: "130 кг", size: "1700 × 780 × 850 мм" }),
    delivery, colors: chairColors, bundles, story: chairStory("prestige-pro", "Prestige Pro"),
  },
  {
    _id: "p-infinity-a350", slug: "infinity-a350", rank: 6, category: "exercise-bikes",
    isNew: true, price: 9_990_000, currency: "UZS",
    title: { ru: "Велотренажёр iSpace Infinity A350", uz: "iSpace Infinity A350 velotrenajyori", en: "iSpace Infinity A350 exercise bike" },
    features: [f.quiet, f.bt],
    images: [{ src: "/images/products/infinity-a350.webp", width: 900, height: 900,
      alt: { ru: "Велотренажёр Infinity A350", uz: "Infinity A350 velotrenajyori", en: "Infinity A350 exercise bike" } }],
    brand: "iSpace", rating: 4.5, reviewCount: 27, inStock: true,
    description: L(
      "Infinity A350 — велотренажёр с магнитной нагрузкой: почти бесшумный ход, восемь уровней сопротивления и Bluetooth для тренировочных приложений.",
      "Infinity A350 — magnit yuklamali velotrenajyor: deyarli shovqinsiz yurish, sakkiz daraja qarshilik va mashg‘ulot ilovalari uchun Bluetooth.",
      "Infinity A350 is a magnetic-resistance exercise bike: near-silent motion, eight resistance levels and Bluetooth for training apps.",
    ),
    specs: fitnessSpecs({ model: "Infinity A350", type: L("Велотренажёр", "Velotrenajyor", "Exercise bike"), power: "—", maxWeight: "120 кг", size: "1100 × 550 × 1400 мм" }),
    delivery,
  },
];
